Add agent metrics configuration and scrape all logs/metrics agent pods
grafana/k8s-monitoring-helm pull request #128
Opened 2023-09-14 00:50 UTC by n888

2023-09-14 00:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k8s-monitoring-helm?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k8s-monitoring-helm?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k8s-monitoring-helm?pullRequest=128) it.</sub>

2023-09-14 19:58 UTC, petewall reviewed
This is really useful. Thanks!

A few changes: I think it's good to scrape more than just the metrics pods, we should be careful about adding too much functionality and customizability before it's really needed. Also, I want to be careful about adding too many more metrics to a default set.

2023-09-14 19:58 UTC, petewall commented on charts/k8s-monitoring/templates/agent_config/_agent.river.txt
> +{{- end }}
Remove this. We haven't needed TLS for the agent, so let's not complicated it until its required.

2023-09-14 19:58 UTC, petewall commented on charts/k8s-monitoring/values.yaml
> +      isTLS: false
Same as in the river, just remove this and hardcode the `http-metrics` port name. This chart controls the deployment of the Grafana Agent, so we don't need ultimate configurability.

2023-09-14 19:58 UTC, petewall commented on charts/k8s-monitoring/values.yaml
> +    - prometheus_remote_storage_shards_min
We gotta really pare this down. The allowList should be a pretty minimal set, unless there's really good reason.
I'd keep it to just `agent_build_info`. I'll look at the rest of the list and see if there's a compelling reason to keep more.

2023-09-14 19:58 UTC, petewall commented on charts/k8s-monitoring/templates/agent_config/_agent.river.txt
> +    regex = "{{- .Values.metrics.agent.pod.port -}}"
Change this back to `regex = "http-metrics"`
I'll explain down below.

2023-09-15 20:59 UTC, n888 commented
@petewall Thanks for the pointers! I have added a blurb for Agent Metrics list in the readme as well (not sure if those links are the best metric list sources)

Please review, cheers

2023-09-18 17:12 UTC, petewall requested changes
This is looking great! One final change, the `README.md` file is actually generated by [helm-docs](https://github.com/norwoodj/helm-docs) from the `README.md.gotmpl` file. Can you move the "### Allow List of Grafana Agent" section to the template file, then run `helm-docs`. That will automatically bring in the changes to the values (it generates that section from reading the values.yaml.

2023-09-18 20:52 UTC, n888 commented
All set, thanks !

2023-09-18 21:39 UTC, petewall commented
One last change required:
The examples are actually generated from the real chart. So, at the top level of the repository, can you run `make regenerate-example-outputs` and add those changes? That should fix the failed checks.

2023-09-18 21:56 UTC, n888 commented
Gotcha -- Pushed :+1:

2023-09-19 00:48 UTC, petewall approved these changes

2023-09-19 01:01 UTC, petewall commented
Another PR just came in. Can you rebase against the latest from main? Much of the content from `grafana-agent-config.yaml` has gone into `_helpers.tpl`. `make regenerate-example-outputs` might be needed again, just FYI.

2023-09-19 01:02 UTC, petewall commented
We'll get this merged!

2023-09-19 20:13 UTC, n888 commented
:+1:
Should be all set, make regen didnt produce any differences

2023-09-19 22:49 UTC, merged

2023-09-19 22:49 UTC, petewall commented
Thanks!
I'm going to do some testing and I'll try and cut a release tomorrow.