Create an extensive doc on config customizations in this chart
grafana/k8s-monitoring-helm pull request #328
Opened 2024-01-08 18:20 UTC by petewall

2024-01-19 15:40 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +These fields adjust how metrics are actually delivered to the metrics service. Tyipcally, these will be changed only to
```suggestion
These fields adjust how metrics are actually delivered to the metrics service. Typically, these will be changed only to
```

2024-01-19 15:43 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +* `extraServices.prometheus.processors` - These processors will control the batch and memory size of metrics to bundle
```suggestion
* `extraServices.prometheus.processors` - These processors control the batch and memory size of metrics to bundle
```

2024-01-19 15:45 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +but this can easily be adjusted.
```suggestion
but you can easily adjust this setting.
```

2024-01-19 15:45 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +* `logs.pod_logs.namespaces` - Only gather logs from pods in the given list of namespaces.
```suggestion
* `logs.pod_logs.namespaces` - Only gather logs from Pods in the given list of namespaces.
```

2024-01-19 15:47 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +* `logs.pod_logs.extraRelabelingRules` - These rules are used to filter from all pods on the cluster to the specific set
```suggestion
* `logs.pod_logs.extraRelabelingRules` - These rules are used to filter from all Pods on the Cluster to the specific set
```

2024-01-19 15:48 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +Customizing this field controls how pod logs are actually gathered from the cluster.
```suggestion
This field controls how Pod logs are gathered from the Cluster.
```

2024-01-19 15:49 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +* `logs.pod_logs.gatherMethod` - The default method, "volumes", means that the Grafana Agent for Logs will gather logs
```suggestion
* `logs.pod_logs.gatherMethod` - The default method, "volumes", means that the Grafana Agent for logs will gather logs
```

2024-01-19 15:49 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +By default, this chart provides a very capable configuration for Kubernetes Cluster infrastructure monitoring. However
```suggestion
By default, this chart provides a very capable configuration for Kubernetes Cluster infrastructure monitoring. However,
```

2024-01-19 15:53 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +  cluster to a specific one that has the metrics. They're used to populate the rules section of a
```suggestion
  Cluster to a specific one that has the metrics. They're used to populate the rules section of a
```

2024-01-19 16:18 UTC, BeverlyJaneJ requested changes

2024-01-19 16:18 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +the Grafana Agent is not detecting the target.
```suggestion
These fields affect how metric targets are discovered. Typically, you'll make changes to these values if the Grafana Agent is not detecting the target.
```

2024-01-25 15:17 UTC, petewall commented
Merged your changes. Thank you so much, @BeverlyJaneJ !

2024-01-26 15:06 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +Metrics are typically gathered using Prometheus-style scraping.
```suggestion
Metrics are usually gathered using Prometheus-style scraping.
```

2024-01-26 15:07 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +These fields affect how metric targets are discovered. Typically, you'll make changes to these values if the Grafana Agent is not detecting the target.
```suggestion
These fields affect how metric targets are discovered. If the Grafana Agent is not detecting the target, make changes to these values.
```

2024-01-26 15:10 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +These fields affect how metric targets are discovered. Typically, you'll make changes to these values if the Grafana Agent is not detecting the target.
In this section, do we need to give some examples of what issues users are trying to solve, such as reducing metrics? For eample, why would I use relabeling for one source as opposed to all?

2024-01-26 15:22 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +By default, we already use an "allow list" to filter to a specific set of metrics, meaning the list drops metrics that are not useful for monitoring Kubernetes Clusters. The following fields allow fo
Again, wondering if we need to say why a user would want to do this.

2024-01-26 15:25 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +tune the performance of metrics uploads.
What's the problem I'm solving?

2024-01-26 15:26 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +### Discovery customizations
```suggestion
### Customize which logs to gather
```

2024-01-26 15:29 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +### Discovery customizations
Probably need an intro sentence here - why would I want to customize log discovery?

2024-01-26 15:31 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +### Gathering customizations
Let's talk to make this section more understandable

2024-01-26 15:31 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +### Processing customizations
```suggestion
### Customize how logs are processed
```

2024-01-26 15:32 UTC, BeverlyJaneJ commented on charts/k8s-monitoring/docs/Customizations.md
> +
Let's talk about this section as well.

2024-01-30 16:11 UTC, BeverlyJaneJ approved these changes

2024-01-30 16:15 UTC, merged