Add templating to extraConfig values
grafana/k8s-monitoring-helm pull request #394
Opened 2024-02-28 08:27 UTC by LeszekBlazewski

This allows templating the `extraConfig` and `logs.extraConfig` values as mentioned in the last section of this issue: https://github.com/grafana/k8s-monitoring-helm/issues/388#issue-2152399437. This could be handy as described in helm tips and tricks -> https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function.

I would use this for example to add the following:

```
extraConfig: |-
  {{- with .Values.externalServices.prometheus }}
  // Mimir rules via PrometheusRule CRD
  mimir.rules.kubernetes "rules" {
    address = nonsensitive(remote.kubernetes.secret.metrics_service.data[{{ .hostKey | quote }}])
  }
  {{- end }}
```

Which allows me to stay in sync with the chart Values file and reuse anything I need (for example when the `hostKey` changes).

If more docs/tests should be added, let me know and I would try to come up with some. The current ones are passing OK (when I executed all of the items from contributing guide).

2024-02-28 08:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k8s-monitoring-helm?pullRequest=394) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k8s-monitoring-helm?pullRequest=394) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k8s-monitoring-helm?pullRequest=394) it.</sub>

2024-02-28 22:27 UTC, petewall requested changes
This is really cool! Thanks for the contribution.

One request: can you update the values.yaml file (and the values section in the README) for this example: https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/custom-config

I'd love to have that example utilize something from this change to showcase what it can do.

2024-02-29 17:58 UTC, LeszekBlazewski commented
Adjusted the custom-config example to showcase the usage of the templating.

2024-02-29 18:16 UTC, petewall approved these changes

2024-03-04 17:08 UTC, merged