feat: Custom External Labels for Prometheus metrics and Loki logs
grafana/k8s-monitoring-helm pull request #77
Opened 2023-08-20 19:00 UTC by roya

This pull request introduces the feature to include custom external labels (e.g. region, cloud, ) to all time series and/or logs forwarded to external systems such as Grafana Cloud.  
Presently only the `cluster` label is specified which is not sufficient when working with multiple clusters and agents.

2023-08-20 19:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k8s-monitoring-helm?pullRequest=77) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k8s-monitoring-helm?pullRequest=77) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k8s-monitoring-helm?pullRequest=77) it.</sub>

2023-08-21 13:36 UTC, skl commented
@roya I added a couple of commits but looks like yours weren't signed, please pull the latest commits and signoff the last 5 commits on this branch as follows:

```shell
git rebase HEAD~5 --signoff
```

Thanks!

2023-08-21 13:50 UTC, petewall requested changes

2023-08-22 08:18 UTC, roya commented on charts/k8s-monitoring/Chart.yaml
> +version: 0.1.6
Updated to 1.0.7 👍

2023-08-22 08:24 UTC, roya commented on examples/custom-config/values.yaml
> +      key4: value4
updated to the suggested examples

2023-08-22 11:14 UTC, skl commented
Thanks for the updates @roya. I've rebased and signed off all commits, @petewall ready for re-review.

2023-08-22 11:48 UTC, petewall approved these changes
Looks great!

2023-08-22 13:10 UTC, merged